"""empty message

Revision ID: abcb8f0715ac
Revises: a8b4d0e38af9
Create Date: 2022-12-25 00:53:55.547622

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "abcb8f0715ac"
down_revision = "a8b4d0e38af9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("password", sa.Text(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("password")

    # ### end Alembic commands ###
